module Languages where

-- This is our type Language. It has two fields, one called languageName, which is the
-- English name for the language and the one we want to show to our users, and the other
-- one is the languageCode which is what we need to use to interface with the API
data Language = Language
  { languageName :: String,
    languageCode :: String
  }
  deriving (Show)

-- This is a hardcoded list of languages and language codes.
languages :: [Language]
languages =
  [ Language "Afrikaans" "af",
    Language "Albanian" "sq",
    Language "Amharic" "am",
    Language "Arabic" "ar",
    Language "Armenian" "hy",
    Language "Azerbaijani" "az",
    Language "Basque" "eu",
    Language "Belarusian" "be",
    Language "Bengali" "bn",
    Language "Bosnian" "bs",
    Language "Bulgarian" "bg",
    Language "Catalan" "ca",
    Language "Cebuano" "ceb",
    Language "Chinese (Simplified)" "zh-CN",
    Language "Corsican" "co",
    Language "Croatian" "hr",
    Language "Czech" "cs",
    Language "Danish" "da",
    Language "Dutch" "nl",
    Language "English" "en",
    Language "Esperanto" "eo",
    Language "Estonian" "et",
    Language "Finnish" "fi",
    Language "French" "fr",
    Language "Frisian" "fy",
    Language "Galician" "gl",
    Language "Georgian" "ka",
    Language "German" "de",
    Language "Greek" "el",
    Language "Gujarati" "gu",
    Language "Haitian Creole" "ht",
    Language "Hausa" "ha",
    Language "Hawaiian" "haw",
    Language "Hebrew" "he",
    Language "Hindi" "hi",
    Language "Hmong" "hmn",
    Language "Hungarian" "hu",
    Language "Icelandic" "is",
    Language "Igbo" "ig",
    Language "Indonesian" "id",
    Language "Irish" "ga",
    Language "Italian" "it",
    Language "Japanese" "ja",
    Language "Javanese" "jv",
    Language "Kannada" "kn",
    Language "Kazakh" "kk",
    Language "Khmer" "km",
    Language "Kinyarwanda" "rw",
    Language "Korean" "ko",
    Language "Kurdish" "ku",
    Language "Kyrgyz" "ky",
    Language "Lao" "lo",
    Language "Latin" "la",
    Language "Latvian" "lv",
    Language "Lithuanian" "lt",
    Language "Luxembourgish" "lb",
    Language "Macedonian" "mk",
    Language "Malagasy" "mg",
    Language "Malay" "ms",
    Language "Malayalam" "ml",
    Language "Maltese" "mt",
    Language "Maori" "mi",
    Language "Marathi" "mr",
    Language "Mongolian" "mn",
    Language "Myanmar (Burmese)" "my",
    Language "Nepali" "ne",
    Language "Norwegian" "no",
    Language "Nyanja (Chichewa)" "ny",
    Language "Odia (Oriya)" "or",
    Language "Pashto" "ps",
    Language "Persian" "fa",
    Language "Polish" "pl",
    Language "Portuguese (Portugal, Brazil)" "pt",
    Language "Punjabi" "pa",
    Language "Romanian" "ro",
    Language "Russian" "ru",
    Language "Samoan" "sm",
    Language "Scots Gaelic" "gd",
    Language "Serbian" "sr",
    Language "Sesotho" "st",
    Language "Shona" "sn",
    Language "Sindhi" "sd",
    Language "Sinhala (Sinhalese)" "si",
    Language "Slovak" "sk",
    Language "Slovenian" "sl",
    Language "Somali" "so",
    Language "Spanish" "es",
    Language "Sundanese" "su",
    Language "Swahili" "sw",
    Language "Swedish" "sv",
    Language "Tagalog (Filipino)" "tl",
    Language "Tajik" "tg",
    Language "Tamil" "ta",
    Language "Tatar" "tt",
    Language "Telugu" "te",
    Language "Thai" "th",
    Language "Turkish" "tr",
    Language "Turkmen" "tk",
    Language "Ukrainian" "uk",
    Language "Urdu" "ur",
    Language "Uyghur" "ug",
    Language "Uzbek" "uz",
    Language "Vietnamese" "vi",
    Language "Welsh" "cy",
    Language "Xhosa" "xh",
    Language "Yiddish" "yi",
    Language "Yoruba" "yo",
    Language "Zulu" "zu"
  ]
